import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; // Corrected import
import CommonLayout from "@/components/CommonLayout"; // Corrected import
import { ThemeProvider } from "@/components/ThemeProvider"; // Corrected import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CommonLayout>
            <Navbar /> {/* Ensure Navbar is included */}
            {children}
          </CommonLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
